default: &default
  adapter: postgresql
  encoding: unicode
  username: shailaja
  password: shailu_123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shailus_db

test:
  <<: *default
  database: shailus_db_test

production:
  <<: *default
  database: shailus_db_production
